In [6]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5591 sha256=1432863333128206938e909efdc32fce8d42b84ce8fd7e9ce13b054bc1e2c26a
  Stored in directory: c:\users\ocac\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [3]:
df['test_score(out of 10)'].median()

8.0

In [4]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df['experience'] = df['experience'].fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
df.experience = df.experience.apply(w2n.word_to_num)
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [10]:
reg = LinearRegression()
reg.fit(df.drop('salary($)',axis='columns'),df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [12]:
reg.intercept_

17737.26346433768

In [13]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [14]:
reg.predict([[12,10,10]])

array([92002.18340611])